### ISSUE TITLE
error in Classify caused by incorrect handling of edge case in PickSeeds: analysis and patch

### ISSUE THREAD

**Issue by GrahamAsher** [publicrepo/rtree#1]
The variables `seed0` and `seed1` are uninitialised (RTree.h, line 1356). In some circumstances, when more than 10 identical items are inserted, they are never assigned to in PickSeeds because the condition `(waste > worst)` is never true. This will cause out-of-range array access in Classify in the expression

`a_parVars->m_taken[a_index]`

The reason the condition `(waste > worst)` is never true in these circumstances is that if `-a_parVars->m_coverSplitArea` has a very large absolute value (for example, -31740137119136332.0, found in my test case), subtracting one from it leaves it unchanged because the value 1 is below the granularity of double-precision floating-point numbers of this magnitude. It is then possible for `waste` and `worst` to have the same value on all passes through the loop in which they are compared.

**The fix is to initialise `seed0` and `seed1` as follows (RTree.h, line 1356):**

`int seed0 = 0, seed1 = 1;`

thus preserving the obviously desired invariant at loop exit that `seed0 != seed1`.

PickSeeds is called in only one place, immediately after InitParVars, which clears all the `m_taken` flags and thus guarantees that indexes 0 and 1 are available.

This bug was found by a user of the [CartoType](https://cartotype.com) map rendering library, which uses RTree. The patch has been tested in CartoType, and fixes the bug to my satisfaction.

**Comment by publicrepo** [comment]
Thanks for reporting and offering a fix Graham.
I see that bug has been present since the original C implementation. Nice catch!

**Comment by GrahamAsher** [comment]
You’re welcome! I’ve also written a unit test and I’ll offer that in a couple of days when I’ve integrated it.

Graham

**Comment by publicrepo** [comment]
Thanks for that.
